dist: trusty
sudo: false

addons:
  apt:
    packages:
      - mysql-server-5.7
      - mysql-client-core-5.7
      - mysql-client-5.7

language: python
cache: pip

python:
  - 2.7

services:
  - mysql

before_install:
  - rm -rf ~/.nvm
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 6
  - npm install -g npm
  - mysql -uroot -e "CREATE USER 'eregs'@'localhost' IDENTIFIED BY 'eregs';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON \`test_%\`.* TO 'eregs'@'localhost';"
  - curl -o- https://dev.mysql.com/get/mysql-apt-config_0.8.6-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.6-1_all.deb

install:
  pip install tox coveralls

before_script:
  - ./setup.sh

script:
  - npm test
  - TOXENV=dj18 tox

after_success:
  coveralls
